web/views.py
from flask import Blueprint, render_template

# from back.models import Article

web_blue = Blueprint('web',__name__)


@web_blue.route('/index/', methods=['GET'])
def index():
    # articles = Article.query.limit(14).all()
    return render_template('web/index.html')


@web_blue.route('/about/', methods=['GET'])
def about():
    return render_template('web/about.html')


@web_blue.route('/gbook/', methods=['GET'])
def gbook():
    return render_template('web/other/gbook.html')

@web_blue.route('/info/', methods=['GET'])
def info():
    return render_template('web/info.html')

@web_blue.route('/infopic/', methods=['GET'])
def infopic():
    return render_template('web/other/infopic.html')

@web_blue.route('/list/', methods=['GET'])
def list():
    return render_template('web/list.html')

@web_blue.route('/share/', methods=['GET'])
def share():
    return render_template('web/other/share.html')





@web_blue.route('/base/', methods=['GET'])
def base():
    return render_template('web/base_main.html')

templates/web/about.html
{% extends 'web/base_main.html' %}

{% block title %}
    about-关于我
{% endblock %}

{% block article %}
    <article>
        {% block aside %}
            <aside class="l_box">
            <div class="about_me">
                <h2>关于我</h2>
                <ul>
                    <i><img src="images/4.jpg"></i>
                    <p><b>杨青</b>，一个80后草根女站长！09年入行。一直潜心研究web前端技术，一边工作一边积累经验，分享一些个人博客模板，以及SEO优化等心得。</p>
                </ul>
            </div>
            <div class="wdxc">
                <h2>我的相册</h2>
                <ul>
                    <li><a href="/"><img src="images/7.jpg"></a></li>
                    <li><a href="/"><img src="images/8.jpg"></a></li>
                    <li><a href="/"><img src="images/9.jpg"></a></li>
                    <li><a href="/"><img src="images/10.jpg"></a></li>
                    <li><a href="/"><img src="images/11.jpg"></a></li>
                    <li><a href="/"><img src="images/12.jpg"></a></li>
                </ul>
            </div>
            <div class="search">
                <form action="/e/search/index.php" method="post" name="searchform" id="searchform">
                    <input name="keyboard" id="keyboard" class="input_text" value="请输入关键字词"
                           style="color: rgb(153, 153, 153);"
                           onfocus="if(value=='请输入关键字词'){this.style.color='#000';value=''}"
                           onblur="if(value==''){this.style.color='#999';value='请输入关键字词'}" type="text">
                    <input name="show" value="title" type="hidden">
                    <input name="tempid" value="1" type="hidden">
                    <input name="tbname" value="news" type="hidden">
                    <input name="Submit" class="input_submit" value="搜索" type="submit">
                </form>
            </div>
            <div class="fenlei">
                <h2>文章分类</h2>
                <ul>
                    <li><a href="/">学无止境（33）</a></li>
                    <li><a href="/">日记（19）</a></li>
                    <li><a href="/">慢生活（520）</a></li>
                    <li><a href="/">美文欣赏（40）</a></li>
                </ul>
            </div>

            <div class="guanzhu">
                <h2>关注我 么么哒</h2>
                <ul>
                    <img src="images/wx.jpg">
                </ul>
            </div>
        </aside>
        {% endblock %}

        {% block main %}
            <main class="r_box">
            <div class="about">
                <p>杨青，女，一个80后草根女站长！09年入行。一直潜心研究web前端技术，一边工作一边积累经验，分享一些个人博客模板，以及SEO优化等心得。我入行早，大家也亲切的叫我&ldquo;青姐&rdquo;。<br/>
                    <br/>
                    SEO奋斗了将近两年时间，个人博客网站百度排名也从之前的30页后，排到了第一页。期间有很多的不容易，但是都没有放弃过。入了这一行，就深深的喜欢上它。我喜欢一句话&ldquo;冥冥中该来则来，无处可逃&rdquo;。<br/>
                    <br/>
                    <img src="images/1.jpg">
                    近几年我也发现个人博客排前几页的也有很多是我做过的模板，感谢各位站长的欣赏，我仔细看过他们的网站。他们在我原模板的基础上有修改，而且他们做的原创内容都是值得一读的。有时候甚至排名都超过了我个人博客网站的排名。<br/>
                    <br/>
                    现在很多人向我请教如何做好SEO，我想说的是，一是&ldquo;代码&rdquo;，一定要简单，布局要合理。二是&ldquo;内容&rdquo;，一定要有原创，伪原创也是可以的。三是&ldquo;持续&rdquo;，这是一个持续性过程，一定要有耐心，SEO不是马上生效的。<br/>
                    <br/>
                    自从入了这一行，也交到了不少朋友，QQ群也不断的壮大起来，280998807(交流群 <span style="color:#FF0000;">已满员</span>)&nbsp;
                    280998843（技术群），群里的小伙伴们也很积极的帮助新朋友解决问题，如果你想加入我们，这个大家庭的门，永远给你敞开！另外微信群已于2018.4.13日开通（已满100，只接受群主邀请，可加我个人微信进群
                    。我的个人微信号 yangqq_1987）</p>
                <br/>
                <br/>
                SEO奋斗了将近两年时间，个人博客网站百度排名也从之前的30页后，排到了第一页。期间有很多的不容易，但是都没有放弃过。入了这一行，就深深的喜欢上它。我喜欢一句话&ldquo;冥冥中该来则来，无处可逃&rdquo;。<br/>
                <br/>
                <img src="images/1.jpg">
                近几年我也发现个人博客排前几页的也有很多是我做过的模板，感谢各位站长的欣赏，我仔细看过他们的网站。他们在我原模板的基础上有修改，而且他们做的原创内容都是值得一读的。有时候甚至排名都超过了我个人博客网站的排名。<br/>
                <br/>
                现在很多人向我请教如何做好SEO，我想说的是，一是&ldquo;代码&rdquo;，一定要简单，布局要合理。二是&ldquo;内容&rdquo;，一定要有原创，伪原创也是可以的。三是&ldquo;持续&rdquo;，这是一个持续性过程，一定要有耐心，SEO不是马上生效的。<br/>
                <br/>
                自从入了这一行，也交到了不少朋友，QQ群也不断的壮大起来，280998807(交流群 <span style="color:#FF0000;">已满员</span>)&nbsp;
                280998843（技术群），群里的小伙伴们也很积极的帮助新朋友解决问题，如果你想加入我们，这个大家庭的门，永远给你敞开！另外微信群已于2018.4.13日开通（已满100，只接受群主邀请，可加我个人微信进群
                。我的个人微信号 yangqq_1987）</p>
                <br/>
                <h2>About my blog</h2>
                &nbsp;
                <p>域 名：www.yangqq.com 创建于2011年01月12日&nbsp;</p>
                <br/>
                <p>服务器：阿里云服务器&nbsp;&nbsp;<a
                        href="https://promotion.aliyun.com/ntms/act/ambassador/sharetouser.html?userCode=8smrzoqa&amp;productCode=vm"
                        target="_blank"><span style="color:#FF0000;"><strong>前往阿里云官网购买&gt;&gt;</strong></span></a></p>
                <br/>
                <p>备案号：蜀ICP备11002373号-1</p>
                <br/>
                <p>程 序：PHP 帝国CMS7.5</p>

            </div>
        </main>
        {% endblock %}

    </article>
{% endblock %}

templates/web/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>
        {% block title %}
        {% endblock %}
    </title>
    {% block css %}
    {% endblock %}

    {% block js1 %}
    {% endblock %}
</head>
<body>
{% block header %}
{% endblock %}

{% block article %}
    {% block aside %}
    {% endblock%}

    {% block main %}
    {% endblock%}

{% endblock %}

{% block footer %}
{% endblock %}

{% block js2 %}
{% endblock %}
<a href="#" class="cd-top">Top</a>
</body>
</html>

templates/web/base_main.html
{% extends 'web/base.html' %}

{% block css %}
<link href="/static/web/css/base.css" rel="stylesheet">
<link href="/static/web/css/index.css" rel="stylesheet">
<link href="/static/web/css/info.css" rel="stylesheet">
<link href="/static/web/css/m.css" rel="stylesheet">
{% endblock %}

{% block js1 %}
<script src="/static/web/js/jquery.min.js" type="text/javascript"></script>

<script type="text/javascript" src="/static/web/js/hc-sticky.js"></script>
<script type="text/javascript" src="/static/web/js/comm.js"></script>
<script src="/static/web/js/scrollReveal.js"></script>
<!--[if lt IE 9]>
<script src="/static/web/js/modernizr.js"></script>
<![endif]-->
{% endblock %}

{% block header %}
<script>jQuery(document).ready(function($){$("html,body").click(function(e){var n=Math.round(Math.random()*100);var $i=$("<b/>").text("+"+n);var x=e.pageX,y=e.pageY;$i.css({"z-index":99999,"top":y-20,"left":x,"position":"absolute","color":"#E94F06"});$("body").append($i);$i.animate({"top":y-180,"opacity":0},1500,function(){$i.remove();});e.stopPropagation();});});</script>
    <header class="header-navigation" id="header">
    <nav>
        <div class="logo"><a href="{{ url_for('web.index') }}">性感龙哥,在线呻吟</a></div>
        <h2 id="mnavh"><span class="navicon"></span></h2>
        <ul id="starlist">
            <li><a href="{{ url_for('web.index') }}">网站首页</a></li>
            <!--<li><a href="share.html">我的相册</a></li>-->
            <li><a href="{{ url_for('web.list') }}">我的文章</a></li>
            <li><a href="{{ url_for('web.about') }}">关于我</a></li>
            <!--<li><a href="gbook.html">留言</a></li>-->
            <li><a href="{{ url_for('web.info') }}">本站热点</a></li>
            <!--<li><a href="infopic.html">照片详情</a></li>-->
        </ul>
    </nav>
</header>
{% endblock %}

{% block footer %}
<footer>
    <p>京公网安备11000002000001号 <a href="https://www.jianshu.com/u/332fe4e135be" target="_blank">侵权必究</a> </p>
</footer>
{% endblock %}

templates/web/index.html

{% extends 'web/base_main.html' %}

{% block title %}
  性感龙哥,在线呻吟
{% endblock %}


{% block article %}
    <article>
        {% block aside %}
            <aside class="l_box">
            <div class="about_me">
              <h2>关于我</h2>
              <ul>
                <i><img src="/static/web/images/4.jpg"></i>
                <p><b>博客</b>人生苦短,我用Python</p>
              </ul>
            </div>

            <div class="search">
              <form action="/e/search/index.php" method="post" name="searchform" id="searchform">
                <input name="keyboard" id="keyboard" class="input_text" value="请输入关键字词" style="color: rgb(153, 153, 153);" onfocus="if(value=='请输入关键字词'){this.style.color='#000';value=''}" onblur="if(value==''){this.style.color='#999';value='请输入关键字词'}" type="text">
                <input name="show" value="title" type="hidden">
                <input name="tempid" value="1" type="hidden">
                <input name="tbname" value="news" type="hidden">
                <input name="Submit" class="input_submit" value="搜索" type="submit">
              </form>
            </div>
            <div class="fenlei">
              <h2>文章分类</h2>
              <ul>
                <li><a href="/">学无止境（33）</a></li>
                <li><a href="/">日记（19）</a></li>
                <li><a href="/">慢生活（520）</a></li>
                <li><a href="/">美文欣赏（40）</a></li>
              </ul>
            </div>
            <div class="links">
              <h2>友情链接</h2>
              <ul>
                <a href="http://www.yangqq.com">杨青个人博客</a> <a href="http://www.yangqq.com">杨青博客</a>
              </ul>
            </div>
            <div class="guanzhu">
              <h2>关注我 么么哒</h2>
              <ul>
                <img src="/static/web/images/wx.jpg">
              </ul>
            </div>
        </aside>
        {% endblock %}

        {% block main %}
            <main class="r_box">
          <li><i><a href="/"><img src="/static/web/images/1.jpg"></a></i>
            <h3><a href="/">你是什么人便会遇上什么人</a></h3>
            <p>有时就为了一句狠话，像心头一口毒钉，永远麻痺着亲密感情交流。恶言，真要慎出，平日多誠心爱语，乃最简易之佈施。</p>
          </li>
          <li><i><a href="/"><img src="/static/web/images/2.jpg"></a></i>
            <h3><a href="/">爱情没有永远，地老天荒也走不完</a></h3>
            <p>也许，爱情没有永远，地老天荒也走不完，生命终结的末端，苦短情长。站在岁月的边端，那些美丽的定格，心伤的绝恋，都被四季的掩埋，一去不返。徒剩下这荒芜的花好月圆，一路相随，流离天涯背负了谁的思念？</p>
          </li>
          <li><i><a href="/"><img src="/static/web/images/3.jpg"></a></i>
            <h3><a href="/">女孩都有浪漫的小情怀——浪漫的求婚词</a></h3>
            <p>还在为浪漫的求婚词而烦恼不知道该怎么说吗？女孩子都有着浪漫的小情怀，对于求婚更是抱着满满的浪漫期待，也希望在求婚那一天对方可以给自己一个最浪漫的求婚词。</p>
          </li>
          <li><i><a href="/"><img src="/static/web/images/4.jpg"></a></i>
            <h3><a href="/">擦肩而过</a></h3>
            <p>《擦肩而过》文/清河鱼 编绘/天朝羽打开一扇窗，我不曾把你想得平常。看季节一一过往。你停留的那个地方，是否依然花儿开放？在夜里守靠着梦中的，想那仿佛前世铭刻进心肠的</p>
          </li>
           <li><i><a href="/"><img src="/static/web/images/1.jpg"></a></i>
            <h3><a href="/">你是什么人便会遇上什么人</a></h3>
            <p>有时就为了一句狠话，像心头一口毒钉，永远麻痺着亲密感情交流。恶言，真要慎出，平日多誠心爱语，乃最简易之佈施。</p>
          </li>
          <li><i><a href="/"><img src="/static/web/images/2.jpg"></a></i>
            <h3><a href="/">爱情没有永远，地老天荒也走不完</a></h3>
            <p>也许，爱情没有永远，地老天荒也走不完，生命终结的末端，苦短情长。站在岁月的边端，那些美丽的定格，心伤的绝恋，都被四季的掩埋，一去不返。徒剩下这荒芜的花好月圆，一路相随，流离天涯背负了谁的思念？</p>
          </li>
          <li><i><a href="/"><img src="/static/web/images/3.jpg"></a></i>
            <h3><a href="/">女孩都有浪漫的小情怀——浪漫的求婚词</a></h3>
            <p>还在为浪漫的求婚词而烦恼不知道该怎么说吗？女孩子都有着浪漫的小情怀，对于求婚更是抱着满满的浪漫期待，也希望在求婚那一天对方可以给自己一个最浪漫的求婚词。</p>
          </li>
          <li><i><a href="/"><img src="/static/web/images/4.jpg"></a></i>
            <h3><a href="/">擦肩而过</a></h3>
            <p>《擦肩而过》文/清河鱼 编绘/天朝羽打开一扇窗，我不曾把你想得平常。看季节一一过往。你停留的那个地方，是否依然花儿开放？在夜里守靠着梦中的，想那仿佛前世铭刻进心肠的</p>
          </li>
          <li>
            <h3><a href="/">女孩都有浪漫的小情怀——浪漫的求婚词</a></h3>
            <p>还在为浪漫的求婚词而烦恼不知道该怎么说吗？女孩子都有着浪漫的小情怀，对于求婚更是抱着满满的浪漫期待，也希望在求婚那一天对方可以给自己一个最浪漫的求婚词。</p>
          </li>
          <li><i><a href="/"><img src="/static/web/images/5.jpg"></a></i>
            <h3><a href="/">擦肩而过</a></h3>
            <p>《擦肩而过》文/清河鱼 编绘/天朝羽打开一扇窗，我不曾把你想得平常。看季节一一过往。你停留的那个地方，是否依然花儿开放？在夜里守靠着梦中的，想那仿佛前世铭刻进心肠的</p>
          </li>
          <li><i><a href="/"><img src="/static/web/images/6.jpg"></a></i>
            <h3><a href="/">女孩都有浪漫的小情怀——浪漫的求婚词</a></h3>
            <p>还在为浪漫的求婚词而烦恼不知道该怎么说吗？女孩子都有着浪漫的小情怀，对于求婚更是抱着满满的浪漫期待，也希望在求婚那一天对方可以给自己一个最浪漫的求婚词。</p>
          </li>
          <li><i><a href="/"><img src="/static/web/images/7.jpg"></a></i>
            <h3><a href="/">你是什么人便会遇上什么人</a></h3>
            <p>有时就为了一句狠话，像心头一口毒钉，永远麻痺着亲密感情交流。恶言，真要慎出，平日多誠心爱语，乃最简易之佈施。</p>
          </li>
          <li><i><a href="/"><img src="/static/web/images/8.jpg"></a></i>
            <h3><a href="/">爱情没有永远，地老天荒也走不完</a></h3>
            <p>也许，爱情没有永远，地老天荒也走不完，生命终结的末端，苦短情长。站在岁月的边端，那些美丽的定格，心伤的绝恋，都被四季的掩埋，一去不返。徒剩下这荒芜的花好月圆，一路相随，流离天涯背负了谁的思念？</p>
          </li>
          <li><i><a href="/"><img src="/static/web/images/9.jpg"></a></i>
            <h3><a href="/">擦肩而过</a></h3>
            <p>《擦肩而过》文/清河鱼 编绘/天朝羽打开一扇窗，我不曾把你想得平常。看季节一一过往。你停留的那个地方，是否依然花儿开放？在夜里守靠着梦中的，想那仿佛前世铭刻进心肠的</p>
          </li>
        </main>
        {% endblock %}
    </article>
{% endblock %}

templates/web/list.html

{% extends 'web/base_main.html' %}


{% block title %}
    list-我的文章
{% endblock %}


{% block article %}
    <article>
        {% block aside %}
            <aside class="l_box">
            <div class="search">
                <form action="/e/search/index.php" method="post" name="searchform" id="searchform">
                    <input name="keyboard" id="keyboard" class="input_text" value="请输入关键字词"
                           style="color: rgb(153, 153, 153);"
                           onfocus="if(value=='请输入关键字词'){this.style.color='#000';value=''}"
                           onblur="if(value==''){this.style.color='#999';value='请输入关键字词'}" type="text">
                    <input name="show" value="title" type="hidden">
                    <input name="tempid" value="1" type="hidden">
                    <input name="tbname" value="news" type="hidden">
                    <input name="Submit" class="input_submit" value="搜索" type="submit">
                </form>
            </div>
            <div class="fenlei">
                <h2>文章分类</h2>
                <ul>
                    <li><a href="/">学无止境（33）</a></li>
                    <li><a href="/">日记（19）</a></li>
                    <li><a href="/">慢生活（520）</a></li>
                    <li><a href="/">美文欣赏（40）</a></li>
                </ul>
            </div>
            <div class="tuijian">
                <h2>站长推荐</h2>
                <ul>
                    <li><a href="/">你是什么人便会遇上什么人</a></li>
                    <li><a href="/">帝国cms 列表页调用子栏目，没有则不显示栏目名称</a></li>
                    <li><a href="/">第二届 优秀个人博客模板比赛参选活动</a></li>
                    <li><a href="/">个人博客模板《绅士》后台管理</a></li>
                    <li><a href="/">你是什么人便会遇上什么人</a></li>
                    <li><a href="/">帝国cms 列表页调用子栏目，没有则不显示栏目名称</a></li>
                    <li><a href="/">第二届 优秀个人博客模板比赛参选活动</a></li>
                    <li><a href="/">个人博客模板《绅士》后台管理</a></li>
                </ul>
            </div>
            <div class="tuijian">
                <h2>点击排行</h2>
                <ul>
                    <li><a href="/">你是什么人便会遇上什么人</a></li>
                    <li><a href="/">帝国cms 列表页调用子栏目，没有则不显示栏目名称</a></li>
                    <li><a href="/">第二届 优秀个人博客模板比赛参选活动</a></li>
                    <li><a href="/">个人博客模板《绅士》后台管理</a></li>
                    <li><a href="/">你是什么人便会遇上什么人</a></li>
                    <li><a href="/">帝国cms 列表页调用子栏目，没有则不显示栏目名称</a></li>
                    <li><a href="/">第二届 优秀个人博客模板比赛参选活动</a></li>
                    <li><a href="/">个人博客模板《绅士》后台管理</a></li>
                </ul>
            </div>
            <div class="cloud">
                <h2>标签云</h2>
                <ul>
                    <a href="/">陌上花开</a> <a href="/">校园生活</a> <a href="/">html5</a> <a href="/">SumSung</a> <a
                        href="/">青春</a> <a href="/">温暖</a> <a href="/">阳光</a> <a href="/">三星</a><a href="/">索尼</a> <a
                        href="/">华维荣耀</a> <a href="/">三星</a> <a href="/">索尼</a>
                </ul>
            </div>
            <div class="guanzhu">
                <h2>关注我 么么哒</h2>
                <ul>
                    <img src="images/wx.jpg">
                </ul>
            </div>
        </aside>
        {% endblock %}

        {% block main %}
            <main class="r_box">
            <li><i><a href="/"><img src="images/1.jpg"></a></i>
                <h3><a href="/">你是什么人便会遇上什么人</a></h3>
                <p>有时就为了一句狠话，像心头一口毒钉，永远麻痺着亲密感情交流。恶言，真要慎出，平日多誠心爱语，乃最简易之佈施。</p>
            </li>
            <li><i><a href="/"><img src="images/2.jpg"></a></i>
                <h3><a href="/">爱情没有永远，地老天荒也走不完</a></h3>
                <p>也许，爱情没有永远，地老天荒也走不完，生命终结的末端，苦短情长。站在岁月的边端，那些美丽的定格，心伤的绝恋，都被四季的掩埋，一去不返。徒剩下这荒芜的花好月圆，一路相随，流离天涯背负了谁的思念？</p>
            </li>
            <li><i><a href="/"><img src="images/3.jpg"></a></i>
                <h3><a href="/">女孩都有浪漫的小情怀——浪漫的求婚词</a></h3>
                <p>还在为浪漫的求婚词而烦恼不知道该怎么说吗？女孩子都有着浪漫的小情怀，对于求婚更是抱着满满的浪漫期待，也希望在求婚那一天对方可以给自己一个最浪漫的求婚词。</p>
            </li>
            <li><i><a href="/"><img src="images/4.jpg"></a></i>
                <h3><a href="/">擦肩而过</a></h3>
                <p>《擦肩而过》文/清河鱼 编绘/天朝羽打开一扇窗，我不曾把你想得平常。看季节一一过往。你停留的那个地方，是否依然花儿开放？在夜里守靠着梦中的，想那仿佛前世铭刻进心肠的</p>
            </li>
            <li>
                <h3><a href="/">女孩都有浪漫的小情怀——浪漫的求婚词</a></h3>
                <p>还在为浪漫的求婚词而烦恼不知道该怎么说吗？女孩子都有着浪漫的小情怀，对于求婚更是抱着满满的浪漫期待，也希望在求婚那一天对方可以给自己一个最浪漫的求婚词。</p>
            </li>
            <li><i><a href="/"><img src="images/5.jpg"></a></i>
                <h3><a href="/">擦肩而过</a></h3>
                <p>《擦肩而过》文/清河鱼 编绘/天朝羽打开一扇窗，我不曾把你想得平常。看季节一一过往。你停留的那个地方，是否依然花儿开放？在夜里守靠着梦中的，想那仿佛前世铭刻进心肠的</p>
            </li>
            <li><i><a href="/"><img src="images/6.jpg"></a></i>
                <h3><a href="/">女孩都有浪漫的小情怀——浪漫的求婚词</a></h3>
                <p>还在为浪漫的求婚词而烦恼不知道该怎么说吗？女孩子都有着浪漫的小情怀，对于求婚更是抱着满满的浪漫期待，也希望在求婚那一天对方可以给自己一个最浪漫的求婚词。</p>
            </li>
            <li><i><a href="/"><img src="images/7.jpg"></a></i>
                <h3><a href="/">你是什么人便会遇上什么人</a></h3>
                <p>有时就为了一句狠话，像心头一口毒钉，永远麻痺着亲密感情交流。恶言，真要慎出，平日多誠心爱语，乃最简易之佈施。</p>
            </li>
            <li><i><a href="/"><img src="images/8.jpg"></a></i>
                <h3><a href="/">爱情没有永远，地老天荒也走不完</a></h3>
                <p>也许，爱情没有永远，地老天荒也走不完，生命终结的末端，苦短情长。站在岁月的边端，那些美丽的定格，心伤的绝恋，都被四季的掩埋，一去不返。徒剩下这荒芜的花好月圆，一路相随，流离天涯背负了谁的思念？</p>
            </li>
            <li><i><a href="/"><img src="images/9.jpg"></a></i>
                <h3><a href="/">擦肩而过</a></h3>
                <p>《擦肩而过》文/清河鱼 编绘/天朝羽打开一扇窗，我不曾把你想得平常。看季节一一过往。你停留的那个地方，是否依然花儿开放？在夜里守靠着梦中的，想那仿佛前世铭刻进心肠的</p>
            </li>
            <div class="pagelist"><a class="allpage"><b>99</b></a>&nbsp;&nbsp;<a href="#"
                                                                                 class="curPage">1</a>&nbsp;&nbsp;<a
                    href="#" onclick="page(2)">2</a>&nbsp;&nbsp;<a href="#" onclick="page(3)">3</a>&nbsp;&nbsp;<a href="#"
                                                                                                                  onclick="page(4)">4</a>&nbsp;&nbsp;<a
                    href="#" onclick="page(5)">5</a>&nbsp;&nbsp;<a href="#" onclick="page(6)">6</a>&nbsp;&nbsp;<a href="#"
                                                                                                                  onclick="page(7)">7</a>&nbsp;&nbsp;<a
                    href="#" onclick="page(8)">8</a>&nbsp;&nbsp;<a href="#" onclick="page(9)">9</a>&nbsp;&nbsp;<a href="#"
                                                                                                                  onclick="page(2)">下一页</a>
            </div>
        </main>
        {% endblock %}
    </article>
{% endblock %}