back/models.py
from datetime import datetime
from flask_sqlalchemy import SQLAlchemy

db = SQLAlchemy()

# 用户类
class User(db.Model):
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    username = db.Column(db.String(20), unique=True, nullable=False)
    password = db.Column(db.String(255),nullable=False)
    is_delete = db.Column(db.Boolean, default=0)
    create_time = db.Column(db.DateTime, default=datetime.now())
    # 定义数据库表名
    __tablename__ = 'user'

    # 定义保存方法
    def save(self):
        db.session.add(self)
        db.session.commit()

# 一对多
# # 文章类型类（一）
class ArticleType(db.Model):
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    # 标题名称
    t_name = db.Column(db.String(30), unique=True,nullable=False)
    # 关联从表
    arts = db.relationship('Article', backref='tp')

    __tablename__ = 'art_type'

#
# # 文章类（多）
class Article(db.Model):
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    title = db.Column(db.String(30), unique=True, nullable=False)
    desc = db.Column(db.String(255), nullable=False)
    content = db.Column(db.TEXT, nullable=False)
    create_time = db.Column(db.DateTime, default=datetime.now())
    # 通过外键声明关系
    type = db.Column(db.Integer,db.ForeignKey('art_type.id'))



# Terminal: python manage.py shell
# from back.models import db
# 创建模型对应表：db.create_all()

back/views.py
from flask import Blueprint, render_template, request, redirect, url_for, session

# 密码的编码与解码
from werkzeug.security import generate_password_hash, check_password_hash

from back.models import User, ArticleType, db, Article
from utils.functools import is_login

back_blue = Blueprint('back', __name__)  # 实例化蓝图


@back_blue.route('/register/', methods=['GET', 'POST'])  # 使用蓝图管理函数
def register():
    if request.method == 'GET':
        return render_template('back/register.html')
    if request.method == 'POST':
        # 获取前端传来的数据
        username = request.form.get('username')
        password = request.form.get('password')
        password2 = request.form.get('password2')
        # 数据校验
        if username and password and password2:
            # 先校验账号，查询数据库
            user = User.query.filter(User.username == username).first()
            if user:
                error = '用户已存在,请重新注册'
                return render_template('back/register.html', error=error)
            else:
                # 校验密码
                if password2 == password:
                    # 保存数据
                    user = User()
                    user.username = username
                    user.password = generate_password_hash(password)
                    user.save()
                    return redirect(url_for('back.login'))

                else:
                    error = '两次密码不一致，请重新输入'
                    return render_template('back/register.html', error=error)
        else:
            error = '请输入完整数据'
            return render_template('back/register.html', error=error)


@back_blue.route('/login/', methods=['GET', 'POST'])
def login():
    if request.method == 'GET':
        return render_template('back/login.html')
    if request.method == 'POST':
        # 获取提交数据数据（post=》form）
        username = request.form.get('username')
        password = request.form.get('password')
        # 数据校验
        if username and password:
            # 先去数据库获取数据
            user = User.query.filter(User.username == username).first()
            if not user:
                error = '账号不存在，请先注册'
                return render_template('back/login.html', error=error)
            if not check_password_hash(user.password, password):
                error = '请核对密码重新输入'
                return render_template('back/login.html', error=error)
            session['user_id'] = user.id  # 状态保持设置session
            return redirect(url_for('back.index') )
        else:
            error = '请填写完整信息'
            return render_template('back/login.html',error=error)


@back_blue.route('/index/', methods=['GET'])
@is_login
def index():
    # 获取session，通过id 拿到用户名  渲染到前端页面
    user_id = session.get('user_id')
    user = User.query.filter(User.id==user_id).first()
    # username = user.username    # bug:如果没有注册过这里会报错
    return render_template('back/index.html')

@back_blue.route('/logout/',methods=['GET'])
@is_login
def logout():
    del session['user_id']
    return redirect(url_for('back.login'))




# ###########################

# 分类相关（显示分类列表）  category.html
@back_blue.route('/a_type/', methods=['GET', 'POST'])
def a_type():
    if request.method == 'GET':
        # 获取所有分类信息
        types = ArticleType.query.all()
        # 渲染到页面
        return render_template('back/category.html',types=types)

# 添加分类,保存信息，然后跳转回分类页面，分类页面获取所有信息
@back_blue.route('/add_category/', methods=['GET', 'POST'])
def add_category():
    if request.method == 'GET':
        return render_template('back/add-category.html')
    if request.method == 'POST':
        atype = request.form.get('atype')
        if atype:
            # 保存分类信息
            art_type = ArticleType()
            art_type.t_name = atype
            db.session.add(art_type)
            db.session.commit()
            return redirect(url_for('back.a_type'))

        else:
            error = '请填写分类信息'
            return render_template('back/add-category.html')


# 删除分类
@back_blue.route('/del_type/<int:id>/', methods=['GET', 'POST'])
def del_type(id):
    atype = ArticleType.query.get(id)
    db.session.delete(atype)
    db.session.commit()
    return redirect(url_for('back.a_type'))

# #############################33

# # 后台首页跳转 文章分类列表
@back_blue.route('/article/',methods=['GET', 'POST'])
def article():
    if request.method == 'GET':
        articles = Article.query.all()
        return render_template('back/article.html', articles=articles)
#
# # 分类列表跳转添加分类页面
@back_blue.route('/add_article/',methods=['GET','POST'])
def add_artilce():
    if request.method == 'GET':
        types = ArticleType.query.all()
        return render_template('back/add-article.html', types=types)  # 反向解析添加文章地质
    if request.method == 'POST':
        print('sdfsdfs')
        title = request.form.get('title')
        desc = request.form.get('desc')
        category = request.form.get('category')
        content = request.form.get('content')
        if title and desc and category and content:
            # 保存数据
            art = Article()
            art.title = title
            art.desc = desc
            art.content = content
            art.type = category
            db.session.add(art)
            db.session.commit()
            return redirect(url_for('back.article'))
        else:
            error = '请填写完整文章信息'
            return render_template('back/add-article.html', error=error)


@back_blue.route('/del_article/<int:id>/', methods=['GET', 'POST'])
def del_article(id):
    a_article = Article.query.get(id)
    db.session.delete(a_article)
    db.session.commit()
    return redirect(url_for('back.article'))


#############################
# 仅仅跳转暂未添加功能
@back_blue.route('/notice/', methods=['GET','POST'])
def notice():
    return render_template('back/notice.html')

@back_blue.route('/comment/', methods=['GET','POST'])
def comment():
    return render_template('back/comment.html')

@back_blue.route('/flink/', methods=['GET','POST'])
def flink():
    return render_template('back/flink.html')

@back_blue.route('/loginlog/', methods=['GET','POST'])
def loginlog():
    return render_template('back/loginlog.html')

@back_blue.route('/manage_user/', methods=['GET','POST'])
def manage_user():
    return render_template('back/manage-user.html')

@back_blue.route('/setting/', methods=['GET','POST'])
def setting():
    return render_template('back/setting.html')


@back_blue.route('/readset/', methods=['GET','POST'])
def readset():
    return render_template('back/readset.html')




#############################
# 后台跳转至前台首页
@back_blue.route('/w_index', methods=['GET'])
def w_index():
    return render_template('web/index.html')

templates/back/add-article.html

{% extends 'back/base_main.html' %}

{% block title%}
    撰写文章-编辑
{% endblock %}

{% block content %}
    <div class="col-sm-9 col-sm-offset-3 col-md-10 col-lg-10 col-md-offset-2 main" id="main">
      <div class="row">
        <form action="" method="post" class="add-article-form">
          {{ error }}
          <div class="col-md-9">
            <h1 class="page-header">撰写新文章</h1>
            <div class="form-group">
              <label for="article-title" class="sr-only">标题</label>
              <input type="text" id="article-title" name="title" class="form-control" placeholder="在此处输入标题" required autofocus autocomplete="off">
            </div>
            <div class="form-group">
              <label for="article-content" class="sr-only">内容</label>
              <script id="article-content" name="content" type="text/plain"></script>
            </div>
            <div class="add-article-box">
              <h2 class="add-article-box-title"><span>描述</span></h2>
              <div class="add-article-box-content">
              	<textarea class="form-control" name="desc" autocomplete="off">描述：</textarea>
                <span class="prompt-text">描述是可选的手工创建的内容总结，并可以在网页描述中使用</span>
              </div>
            </div>
          </div>
          <div class="col-md-3">
            <h1 class="page-header">操作</h1>
            <div class="add-article-box">
              <h2 class="add-article-box-title"><span>栏目</span></h2>
              <div class="add-article-box-content">
                <ul class="category-list">
                  {% for type in types %}
                    <li>
                      <label>
                        <input name="category" type="radio" value="{{ type.id }}" checked>
                        {{ type.t_name }} <em class="hidden-md">( 栏目ID: <span>1</span> )</em></label>
                    </li>
                  {% endfor %}
                </ul>
              </div>
            </div>
            <div class="add-article-box">
              <h2 class="add-article-box-title"><span>发布</span></h2>
              <div class="add-article-box-footer">
                <button class="btn btn-primary" type="submit" name="submit">发布</button>
              </div>
            </div>
          </div>
        </form>
      </div>
    </div>
{% endblock %}


{% block js2 %}
<script src="/static/back/js/bootstrap.min.js"></script>
<script src="/static/back/js/admin-scripts.js"></script>
<script src="/static/back/lib/ueditor/ueditor.config.js"></script>
<script src="/static/back/lib/ueditor/ueditor.all.min.js"> </script>
<script src="/static/back/lib/ueditor/lang/zh-cn/zh-cn.js"></script>
<script id="uploadEditor" type="text/plain" style="display:none;"></script>
<script>
var editor = UE.getEditor('article-content');
window.onresize=function(){
    window.location.reload();
}
var _uploadEditor;
$(function () {
    //重新实例化一个编辑器，防止在上面的editor编辑器中显示上传的图片或者文件
    _uploadEditor = UE.getEditor('uploadEditor');
    _uploadEditor.ready(function () {
        //设置编辑器不可用
        //_uploadEditor.setDisabled();
        //隐藏编辑器，因为不会用到这个编辑器实例，所以要隐藏
        _uploadEditor.hide();
        //侦听图片上传
        _uploadEditor.addListener('beforeInsertImage', function (t, arg) {
            //将地址赋值给相应的input,只去第一张图片的路径
            $("#pictureUpload").attr("value", arg[0].src);
            //图片预览
            //$("#imgPreview").attr("src", arg[0].src);
        })
        //侦听文件上传，取上传文件列表中第一个上传的文件的路径
        _uploadEditor.addListener('afterUpfile', function (t, arg) {
            $("#fileUpload").attr("value", _uploadEditor.options.filePath + arg[0].url);
        })
    });
});
</script>
{% endblock %}

templates/back/add-category.html
{% extends 'back/category.html' %}

{% block cate %}
    <div class="col-md-5">
      <h1 class="page-header">添加文章分类</h1>
      <form action="" method="post" autocomplete="off">
          {{ error }}
        <div class="form-group">
          <label for="category-name">栏目名称</label>
          <input type="text" id="category-name" name="atype" class="form-control" placeholder="在此处输入栏目名称" required autocomplete="off">
          <span class="prompt-text">这将是它在站点上显示的名字。</span> </div>
        <button class="btn btn-primary" type="submit" name="name">添加新栏目</button>
      </form>
    </div>
{% endblock %}

{% block manage %}
{% endblock %}

templates/back/add-notice.html
<!doctype html>
<html lang="zh-CN">
<head>
<meta charset="utf-8">
<meta name="renderer" content="webkit">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>写公告 - 异清轩博客管理系统</title>
<link rel="stylesheet" type="text/css" href="/static/back/css/bootstrap.min.css">
<link rel="stylesheet" type="text/css" href="/static/back/css/style.css">
<link rel="stylesheet" type="text/css" href="/static/back/css/font-awesome.min.css">
<link rel="apple-touch-icon-precomposed" href="/static/back/images/icon/icon.png">
<link rel="shortcut icon" href="/static/back/images/icon/favicon.ico">
<script src="/static/back/js/jquery-2.1.4.min.js"></script>
<!--[if gte IE 9]>
    <script src="/static/back/js/jquery-1.11.1.min.js"
            type="text/javascript"></script>
    <script src="/static/back/js/html5shiv.min.js" type="text/javascript"></script>
    <script src="/static/back/js/respond.min.js" type="text/javascript"></script>
    <script src="/static/back/js/selectivizr-min.js"
            type="text/javascript"></script>
    <![endif]-->
<!--[if lt IE 9]>
  <script>window.location.href='upgrade-browser.html';</script>
<![endif]-->
</head>

<body class="user-select">
<section class="container-fluid">
  <header>
    <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false"> <span class="sr-only">切换导航</span> <span class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span> </button>
          <a class="navbar-brand" href="/">YlsatCMS</a> </div>
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav navbar-right">
            <li><a href="">消息 <span class="badge">1</span></a></li>
            <li class="dropdown"> <a class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">admin <span class="caret"></span></a>
              <ul class="dropdown-menu dropdown-menu-left">
                <li><a title="查看或修改个人信息" data-toggle="modal" data-target="#seeUserInfo">个人信息</a></li>
                <li><a title="查看您的登录记录" data-toggle="modal" data-target="#seeUserLoginlog">登录记录</a></li>
              </ul>
            </li>
            <li><a href="login.html" onClick="if(!confirm('是否确认退出？'))return false;">退出登录</a></li>
            <li><a data-toggle="modal" data-target="#WeChat">帮助</a></li>
          </ul>
          <form action="" method="post" class="navbar-form navbar-right" role="search">
            <div class="input-group">
              <input type="text" class="form-control" autocomplete="off" placeholder="键入关键字搜索" maxlength="15">
              <span class="input-group-btn">
              <button class="btn btn-default" type="submit">搜索</button>
              </span> </div>
          </form>
        </div>
      </div>
    </nav>
  </header>
  <div class="row">
    <aside class="col-sm-3 col-md-2 col-lg-2 sidebar">
      <ul class="nav nav-sidebar">
        <li><a href="index.html">报告</a></li>
      </ul>
      <ul class="nav nav-sidebar">
        <li><a href="article.html">文章</a></li>
        <li class="active"><a href="notice.html">公告</a></li>
        <li><a href="comment.html">评论</a></li>
        <li><a data-toggle="tooltip" data-placement="top" title="网站暂无留言功能">留言</a></li>
      </ul>
      <ul class="nav nav-sidebar">
        <li><a href="category.html">栏目</a></li>
        <li><a class="dropdown-toggle" id="otherMenu" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">其他</a>
          <ul class="dropdown-menu" aria-labelledby="otherMenu">
            <li><a href="flink.html">友情链接</a></li>
            <li><a href="loginlog.html">访问记录</a></li>
          </ul>
        </li>
      </ul>
      <ul class="nav nav-sidebar">
        <li><a class="dropdown-toggle" id="userMenu" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">用户</a>
          <ul class="dropdown-menu" aria-labelledby="userMenu">
            <li><a href="#">管理用户组</a></li>
            <li><a href="manage-user.html">管理用户</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="loginlog.html">管理登录日志</a></li>
          </ul>
        </li>
        <li><a class="dropdown-toggle" id="settingMenu" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">设置</a>
          <ul class="dropdown-menu" aria-labelledby="settingMenu">
            <li><a href="setting.html">基本设置</a></li>
            <li><a href="readset.html">用户设置</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">安全配置</a></li>
            <li role="separator" class="divider"></li>
            <li class="disabled"><a>扩展菜单</a></li>
          </ul>
        </li>
      </ul>
    </aside>
    <div class="col-sm-9 col-sm-offset-3 col-md-10 col-lg-10 col-md-offset-2 main" id="main">
      <div class="row">
        <form action="test.php" method="post" class="add-article-form">
          <div class="col-md-9">
            <h1 class="page-header">撰写新公告</h1>
            <div class="form-group">
              <label for="article-title" class="sr-only">标题</label>
              <input type="text" id="article-title" name="title" class="form-control" placeholder="在此处输入标题" required autofocus autocomplete="off">
            </div>
            <div class="form-group">
              <label for="article-content" class="sr-only">内容</label>
              <textarea id="article-content" name="content" class="form-control"></textarea> 
            </div>
            <div class="add-article-box">
              <h2 class="add-article-box-title"><span>关键字</span></h2>
              <div class="add-article-box-content">
              	<input type="text" class="form-control" placeholder="请输入关键字" name="keywords" autocomplete="off">
                <span class="prompt-text">多个标签请用英文逗号,隔开。</span>
              </div>
            </div>
            <div class="add-article-box">
              <h2 class="add-article-box-title"><span>描述</span></h2>
              <div class="add-article-box-content">
              	<textarea class="form-control" name="describe" autocomplete="off"></textarea>
                <span class="prompt-text">描述是可选的手工创建的内容总结，并可以在网页描述中使用</span>
              </div>
            </div>
          </div>
          <div class="col-md-3">
            <h1 class="page-header">操作</h1>
            <div class="add-article-box">
              <h2 class="add-article-box-title"><span>发布</span></h2>
              <div class="add-article-box-content">
              	<p><label>状态：</label><span class="article-status-display">未发布</span></p>
                <p><label>公开度：</label><input type="radio" name="visibility" value="0" checked/>公开 <input type="radio" name="visibility" value="1" />加密</p>
                <p><label>发布于：</label><span class="article-time-display"><input style="border: none;" type="datetime" name="time" value="2016-01-09 17:29:37" /></span></p>
              </div>
              <div class="add-article-box-footer">
                <button class="btn btn-primary" type="submit" name="submit">发布</button>
              </div>
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>
</section>
<!--个人信息模态框-->
<div class="modal fade" id="seeUserInfo" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <form action="" method="post">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <h4 class="modal-title" >个人信息</h4>
        </div>
        <div class="modal-body">
          <table class="table" style="margin-bottom:0px;">
            <thead>
              <tr> </tr>
            </thead>
            <tbody>
              <tr>
                <td wdith="20%">姓名:</td>
                <td width="80%"><input type="text" value="王雨" class="form-control" name="truename" maxlength="10" autocomplete="off" /></td>
              </tr>
              <tr>
                <td wdith="20%">用户名:</td>
                <td width="80%"><input type="text" value="admin" class="form-control" name="username" maxlength="10" autocomplete="off" /></td>
              </tr>
              <tr>
                <td wdith="20%">电话:</td>
                <td width="80%"><input type="text" value="18538078281" class="form-control" name="usertel" maxlength="13" autocomplete="off" /></td>
              </tr>
              <tr>
                <td wdith="20%">旧密码:</td>
                <td width="80%"><input type="password" class="form-control" name="old_password" maxlength="18" autocomplete="off" /></td>
              </tr>
              <tr>
                <td wdith="20%">新密码:</td>
                <td width="80%"><input type="password" class="form-control" name="password" maxlength="18" autocomplete="off" /></td>
              </tr>
              <tr>
                <td wdith="20%">确认密码:</td>
                <td width="80%"><input type="password" class="form-control" name="new_password" maxlength="18" autocomplete="off" /></td>
              </tr>
            </tbody>
            <tfoot>
              <tr></tr>
            </tfoot>
          </table>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">取消</button>
          <button type="submit" class="btn btn-primary">提交</button>
        </div>
      </div>
    </form>
  </div>
</div>
<!--个人登录记录模态框-->
<div class="modal fade" id="seeUserLoginlog" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" >登录记录</h4>
      </div>
      <div class="modal-body">
        <table class="table" style="margin-bottom:0px;">
          <thead>
            <tr>
              <th>登录IP</th>
              <th>登录时间</th>
              <th>状态</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>::1:55570</td>
              <td>2016-01-08 15:50:28</td>
              <td>成功</td>
            </tr>
            <tr>
              <td>::1:64377</td>
              <td>2016-01-08 10:27:44</td>
              <td>成功</td>
            </tr>
            <tr>
              <td>::1:64027</td>
              <td>2016-01-08 10:19:25</td>
              <td>成功</td>
            </tr>
            <tr>
              <td>::1:57081</td>
              <td>2016-01-06 10:35:12</td>
              <td>成功</td>
            </tr>
          </tbody>
        </table>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">朕已阅</button>
      </div>
    </div>
  </div>
</div>
<!--微信二维码模态框-->
<div class="modal fade user-select" id="WeChat" tabindex="-1" role="dialog" aria-labelledby="WeChatModalLabel">
  <div class="modal-dialog" role="document" style="margin-top:120px;max-width:280px;">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="WeChatModalLabel" style="cursor:default;">微信扫一扫</h4>
      </div>
      <div class="modal-body" style="text-align:center"> <img src="/static/back/images/weixin.jpg" alt="" style="cursor:pointer"/> </div>
    </div>
  </div>
</div>
<!--提示模态框-->
<div class="modal fade user-select" id="areDeveloping" tabindex="-1" role="dialog" aria-labelledby="areDevelopingModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="areDevelopingModalLabel" style="cursor:default;">该功能正在日以继夜的开发中…</h4>
      </div>
      <div class="modal-body"> <img src="/static/back/images/baoman/baoman_01.gif" alt="深思熟虑" />
        <p style="padding:15px 15px 15px 100px; position:absolute; top:15px; cursor:default;">很抱歉，程序猿正在日以继夜的开发此功能，本程序将会在以后的版本中持续完善！</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-primary" data-dismiss="modal">朕已阅</button>
      </div>
    </div>
  </div>
</div>
<!--右键菜单列表-->
<div id="rightClickMenu">
  <ul class="list-group rightClickMenuList">
    <li class="list-group-item disabled">欢迎访问异清轩博客</li>
    <li class="list-group-item"><span>IP：</span>172.16.10.129</li>
    <li class="list-group-item"><span>地址：</span>河南省郑州市</li>
    <li class="list-group-item"><span>系统：</span>Windows10 </li>
    <li class="list-group-item"><span>浏览器：</span>Chrome47</li>
  </ul>
</div>
<script src="/static/back/js/bootstrap.min.js"></script>
<script src="/static/back/js/admin-scripts.js"></script>
<!--summernote富文本编辑器-->
<link rel="stylesheet" type="text/css" href="/static/back/lib/summernote/summernote.css">
<script src="/static/back/lib/summernote/summernote.js"></script>
<script src="/static/back/lib/summernote/lang/summernote-zh-CN.js"></script>
<script>
$('#article-content').summernote({
	lang: 'zh-CN'
});
</script>
</body>
</html>

templates/back/category.html

{% extends 'back/base_main.html' %}

{% block title %}
    文章栏目-分类
{% endblock %}

{% block content %}
    <div class="col-sm-9 col-sm-offset-3 col-md-10 col-lg-10 col-md-offset-2 main" id="main">
      <div class="row">
        {% block cate %}
        {% endblock %}
        {% block manage %}

        <div class="col-md-7">
          <h1 class="page-header">管理 <span class="badge"></span></h1>
          <p> <a href="{{ url_for('back.add_category') }}"> <button><b>添加分类</b></button> </a></p>
          <div class="table-responsive">
            <table class="table table-striped table-hover">
              <thead>
                <tr>
                  <th><span class="glyphicon glyphicon-star"></span> <span class="visible-lg">ID</span></th>
                  <th><span class="glyphicon glyphicon-file"></span> <span class="visible-lg">名称</span></th>
                  <th><span class="glyphicon glyphicon-pencil"></span> <span class="visible-lg">操作</span></th>
                </tr>
              </thead>
              <tbody>
                {% for type in types %}
                <tr>
                  <td>{{ type.id }}</td>
                  <td>{{ type.t_name }}</td>
                  <td><a href="update-category.html">修改</a> <a href="{{ url_for('back.del_type', id=type.id) }}">删除</a></td>
                </tr>
                {% endfor %}
              </tbody>
            </table>
            <span class="prompt-text"><strong>注：</strong>删除一个栏目也会删除栏目下的文章和子栏目,请谨慎删除!</span> </div>
        </div>
        {% endblock %}
      </div>
    </div>
{% endblock %}

{% block js2 %}
<script src="/static/back/js/bootstrap.min.js"></script>
<script src="/static/back/js/admin-scripts.js"></script>
<!--<script>-->
<!--//是否确认删除-->
<!--$(function(){   -->
	<!--$("#main table tbody tr td a").click(function(){-->
		<!--var name = $(this);-->
		<!--var id = name.attr("rel"); //对应id  -->
		<!--if (event.srcElement.outerText === "删除") -->
		<!--{-->
			<!--if(window.confirm("此操作不可逆，是否确认？"))-->
			<!--{-->
				<!--$.ajax({-->
					<!--type: "POST",-->
					<!--url: "/Category/delete",-->
					<!--data: "id=" + id,-->
					<!--cache: false, //不缓存此页面   -->
					<!--success: function (data) {-->
						<!--window.location.reload();-->
					<!--}-->
				<!--});-->
			<!--};-->
		<!--};-->
	<!--});   -->
<!--});-->
<!--</script>-->
{% endblock %}